#!/bin/bash

#SBATCH --job-name="plot_test_shapley_maps"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --nodes=1
#SBATCH --ntasks=8           # 8 tasks per node
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=8  # 8 GPUs per node
#SBATCH --exclusive
#SBATCH --time=01:00:00
#SBATCH --array=5-7,13-15
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=plot_test_shapley_maps_%A_%a.out

module load imagemagick/7.1.1-11
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_wildfire_wpo_standalone/ml_for_wildfire_wpo"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_wildfire_models/experiment19/mountain_central_west"

GFS_DIR_NAME="/scratch2/BMC/gsd-hpcs/Ryan.Lagerquist/ml_for_wildfire_wpo_project/gfs_data/processed"
TARGET_DIR_NAME="/scratch2/BMC/gsd-hpcs/Ryan.Lagerquist/ml_for_wildfire_wpo_project/canadian_fwi"
GFS_FORECAST_TARGET_DIR_NAME="/scratch2/BMC/gsd-hpcs/Ryan.Lagerquist/ml_for_wildfire_wpo_project/gfs_data/processed_fwi_forecasts"
ERA5_CONSTANT_FILE_NAME="/scratch2/BMC/gsd-hpcs/Ryan.Lagerquist/ml_for_wildfire_wpo_project/era5_constants.nc"

LEAD_TIMES_DAYS=("03" "03" "03" "03" "03" "03" "03" "03" "03" "03" "05" "05" "05" "05" "05" "05" "05" "05" "05" "05" "07" "07" "07" "07" "07" "07" "07" "07" "07" "07")
SPECTRAL_COMPLEXITIES=("050" "050" "075" "075" "100" "100" "125" "125" "150" "150" "050" "050" "075" "075" "100" "100" "125" "125" "150" "150" "050" "050" "075" "075" "100" "100" "125" "125" "150" "150")
CONVNEXT_FLAGS=("0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1")

BEST_MODEL_INDEX=3

lead_time_days=${LEAD_TIMES_DAYS[$BEST_MODEL_INDEX]}
spectral_complexity=${SPECTRAL_COMPLEXITIES[$BEST_MODEL_INDEX]}
convnext_flag=${CONVNEXT_FLAGS[$BEST_MODEL_INDEX]}

model_dir_name="${TOP_MODEL_DIR_NAME}/lead-time-days=${lead_time_days}_spectral-complexity=${spectral_complexity}_use-convnext=${convnext_flag}"
echo $model_dir_name

shapley_file_name="${model_dir_name}/validation/test_shapley_maps/shapley_maps_20210809.nc"
output_dir_name="${model_dir_name}/validation/test_shapley_maps/shapley_maps_20210809"

python3 -u "${CODE_DIR_NAME}/plot_shapley_maps.py" \
--input_shapley_file_name="${shapley_file_name}" \
--input_gfs_directory_name="${GFS_DIR_NAME}" \
--input_target_dir_name="${TARGET_DIR_NAME}" \
--input_gfs_fcst_target_dir_name="${GFS_FORECAST_TARGET_DIR_NAME}" \
--input_gfs_norm_file_name="/scratch2/BMC/gsd-hpcs/Ryan.Lagerquist/ml_for_wildfire_wpo_project/gfs_data/processed/normalization_params_2019-2020.nc" \
--predictor_colour_limits_prctile 0.1 99.9 \
--shapley_colour_limits_prctile 5.0 99.9 \
--region_name="Colorado" \
--shapley_line_width=4 \
--shapley_line_opacity=0.8 \
--plot_latitude_limits_deg_n 31 47 \
--plot_longitude_limits_deg_e 244 262 \
--shapley_half_num_contours=10 \
--plot_shapley_in_log_space=0 \
--shapley_smoothing_radius_px=2 \
--output_dir_name="${output_dir_name}"
