#!/bin/bash

#SBATCH --job-name="plot_hyperparam_grids"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=02:00:00
#SBATCH --array=0-9
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=plot_hyperparam_grids_%A_%a.out

module load imagemagick/7.1.1-11
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_wildfire_wpo_standalone/ml_for_wildfire_wpo"
TOP_MODEL_DIR_NAME="/scratch2/STI/mdl-sti/Ryan.Lagerquist/ml_for_wildfire_models/experiment16_all_leads"

MODEL_LEAD_TIMES_DAYS=(1 2 3 4 5 6 7 8 9 10)

python3 -u "${CODE_DIR_NAME}/plot_hyperparam_grids_exp16.py" \
--experiment_dir_name="${TOP_MODEL_DIR_NAME}" \
--model_lead_time_days=${MODEL_LEAD_TIMES_DAYS[$SLURM_ARRAY_TASK_ID]} \
--target_field_names "fine_fuel_moisture_code" "duff_moisture_code" "drought_code" "initial_spread_index" "buildup_index" "fire_weather_index" "daily_severity_rating"
