#!/bin/tcsh

#SBATCH --job-name="train_neural_net"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --nodes=1
#SBATCH --ntasks=8           # 8 tasks per node
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=8  # 8 GPUs per node
#SBATCH --exclusive
#SBATCH --time=30:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=train_neural_nets_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_wildfire_wpo_standalone/ml_for_wildfire_wpo"
set TEMPLATE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_wildfire_models/training_test_with_lagged_targets/template"
set OUTPUT_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_wildfire_models/training_test_with_lagged_targets"

set GFS_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_wildfire_wpo_project/gfs_data/processed/merged"
set GFS_NORM_FILE_NAME="${GFS_DIR_NAME}/z_score_params_quickie.nc"
set TARGET_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_wildfire_wpo_project/canadian_fwi"
set TARGET_NORM_FILE_NAME="${TARGET_DIR_NAME}/z_score_params_2019-and-2021-offseason.nc"

python3 -u "${CODE_DIR_NAME}/train_neural_net.py" \
--input_template_file_name="${TEMPLATE_DIR_NAME}/model.h5" \
--output_model_dir_name="${OUTPUT_DIR_NAME}" \
--inner_latitude_limits_deg_n 17 73 \
--inner_longitude_limits_deg_e 171 -65 \
--outer_latitude_buffer_deg=5 \
--outer_longitude_buffer_deg=5 \
--gfs_predictor_field_names "temperature_kelvins" "specific_humidity_kg_kg01" "geopotential_height_m_asl" "u_wind_m_s01" "v_wind_m_s01" "temperature_2m_agl_kelvins" "specific_humidity_2m_agl_kg_kg01" "u_wind_10m_agl_m_s01" "v_wind_10m_agl_m_s01" "accumulated_precip_metres" "volumetric_soil_moisture_fraction_0to10cm" "snow_depth_metres" \
--gfs_pressure_levels_mb 500 700 900 \
--gfs_predictor_lead_times_hours 0 12 24 36 48 \
--gfs_normalization_file_name="${GFS_NORM_FILE_NAME}" \
--era5_constant_file_name="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_wildfire_wpo_project/era5_constants.nc" \
--target_field_name="fine_fuel_moisture_code" \
--target_lead_time_days=2 \
--target_lag_times_days 1 2 3 \
--target_normalization_file_name="${TARGET_NORM_FILE_NAME}" \
--num_examples_per_batch=8 \
--sentinel_value=-10 \
--gfs_dir_name_for_training="${GFS_DIR_NAME}" \
--target_dir_name_for_training="${TARGET_DIR_NAME}" \
--gfs_init_date_limit_strings_for_training "20190101" "20191231" \
--gfs_dir_name_for_validation="${GFS_DIR_NAME}" \
--target_dir_name_for_validation="${TARGET_DIR_NAME}" \
--gfs_init_date_limit_strings_for_validation "20210501" "20211031" \
--num_epochs=1000 \
--num_training_batches_per_epoch=16 \
--num_validation_batches_per_epoch=8
