#!/bin/bash

#SBATCH --job-name="evaluate_neural_nets_gridded"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=12:00:00
#SBATCH --array=0-13
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=evaluate_neural_nets_gridded_%A_%a.out

conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_wildfire_wpo_standalone/ml_for_wildfire_wpo"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_wildfire_models/experiment18_lf_test"

model_dir_name="${TOP_MODEL_DIR_NAME}/training-strategy=20-50-diff-plus2days_spectral-complexity=090_use-residual-blocks=0_use-lead-time-as-predictor=0"
echo $model_dir_name

MODEL_LEAD_TIMES_DAYS=("01" "02" "03" "04" "05" "06" "07" "08" "09" "10" "11" "12" "13" "14")

python3 -u "${CODE_DIR_NAME}/evaluate_model.py" \
--input_prediction_dir_name="${model_dir_name}/validation_lead-time-days=${MODEL_LEAD_TIMES_DAYS[$SLURM_ARRAY_TASK_ID]}/isotonic_regression/uncertainty_calibration" \
--init_date_limit_strings "20210101" "20211210" \
--num_bootstrap_reps=1 \
--target_field_names "fine_fuel_moisture_code" "duff_moisture_code" "drought_code" "initial_spread_index" "buildup_index" "fire_weather_index" "daily_severity_rating" \
--num_relia_bins_by_target 10 10 10 10 10 10 10 \
--min_relia_bin_edge_by_target 0 0 0 0 0 0 0 \
--max_relia_bin_edge_by_target 99 1000 2500 65 1000 130 150 \
--per_grid_cell=1 \
--keep_it_simple=1 \
--compute_ssrat=1 \
--output_file_name="${model_dir_name}/validation_lead-time-days=${MODEL_LEAD_TIMES_DAYS[$SLURM_ARRAY_TASK_ID]}/isotonic_regression/uncertainty_calibration/gridded_evaluation.nc"
